/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description OK
 */
export const getHealth200Schema = z.any()

export const getHealthQueryResponseSchema = z.lazy(() => getHealth200Schema)