/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description OK
*/
export type GetHealth200 = any;

export type GetHealthQueryResponse = GetHealth200;

export type GetHealthQuery = {
    Response: GetHealth200;
    Errors: any;
};